GET http://localhost:5000/api/users/me HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTc1MDc0ODU1N30.p9gV_8wi1FF6vv1XFuEkdKvjghFEMVUUQ5rJzjeyW0Q

###

POST http://localhost:5000/api/users/register HTTP/1.1
content-type: application/json

{
    "username": "superadmin3",
    "password": "Pas$w0rd"
}

###

POST http://localhost:5000/api/users/login HTTP/1.1
content-type: application/json

{
    "username": "superadmin3",
    "password": "Pas$w0rd"
}

###

GET http://localhost:5000/api/wallet/saldo HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFhNDU3YmRhLWNhNWUtNDJlYi05NmM4LTA1ZTliOTg0NzE4NSIsInVzZXJuYW1lIjoic3VwZXJhZG1pbjMiLCJpYXQiOjE3NTA4MzgxNTYsImV4cCI6MTc1MDg0MTc1Nn0.KixTHBU5_I9-prSgG8B8pm7NjUzbJPIitchkufm3nSc

###

PUT http://localhost:5000/api/wallet/topup HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFhNDU3YmRhLWNhNWUtNDJlYi05NmM4LTA1ZTliOTg0NzE4NSIsInVzZXJuYW1lIjoic3VwZXJhZG1pbjMiLCJpYXQiOjE3NTA4MzgxNTYsImV4cCI6MTc1MDg0MTc1Nn0.KixTHBU5_I9-prSgG8B8pm7NjUzbJPIitchkufm3nSc

{
    "amount": 1000000000000
}

###

PUT http://localhost:5000/api/wallet/deduct HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFhNDU3YmRhLWNhNWUtNDJlYi05NmM4LTA1ZTliOTg0NzE4NSIsInVzZXJuYW1lIjoic3VwZXJhZG1pbjMiLCJpYXQiOjE3NTA4MzgxNTYsImV4cCI6MTc1MDg0MTc1Nn0.KixTHBU5_I9-prSgG8B8pm7NjUzbJPIitchkufm3nSc

{
    "amount": 1000000000000
}


