GET http://localhost:5000/api/users/me HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTc1MDc0ODU1N30.p9gV_8wi1FF6vv1XFuEkdKvjghFEMVUUQ5rJzjeyW0Q

###

POST http://localhost:5000/api/users/register HTTP/1.1
content-type: application/json

{
    "username": "superadmin2",
    "password": "z$446666G"
}

###

POST http://localhost:5000/api/users/login HTTP/1.1
content-type: application/json

{
    "username": "superadmin2",
    "password": "z$446666G"
}

###

GET http://localhost:5000/api/wallet/ HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywidXNlcm5hbWUiOiJzdXBlcmFkbWluMiIsImlhdCI6MTc1MDgyMDQ5MCwiZXhwIjoxNzUwODI0MDkwfQ.j95bgVOc81va3Uz90E_mInwV9ntq6QgF2GbUNkIjEa0

###

PUT http://localhost:5000/api/wallet/topup HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywidXNlcm5hbWUiOiJzdXBlcmFkbWluMiIsImlhdCI6MTc1MDgxODk5Nn0.NMrcgp5NeTjJVToBF39ziKObZ36lxhQAA4uLWYL8TEA

{
    "amount": 1000000000000
}

###

PUT http://localhost:5000/api/wallet/deduct HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywidXNlcm5hbWUiOiJzdXBlcmFkbWluMiIsImlhdCI6MTc1MDgxODk5Nn0.NMrcgp5NeTjJVToBF39ziKObZ36lxhQAA4uLWYL8TEA

{
    "amount": 1000000000000
}


